#!/usr/bin/python3


"""Importing module for getting the argv and exit"""


import sys
ac = len(sys.argv)
if(ac != 2):
    sys.exit(f"Usage: {sys.argv[0]} <file>")


"""Finding natural factors of a number"""


def factorizer(n):
    p = 2
    
    if (n < 2):
        return

    while (n % p):
        p += 1
    
    print("{} = {:.0f} * {}".format(n, n/p, p))

"""Opening a test file containing test cases(n)"""


def file_open(file):
    with open(file) as f:
        for num in f:
            num = int(num)
            factorizer(num)
    f.close()

file_open(sys.argv[1])
